name: Release

on:
  push:
    branches:
      - initial-lmd-core
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    name: Publish JSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
